# Generated by Django 4.1.7 on 2023-03-15 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='item_category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='item_subcategory',
            new_name='subcategory_name',
        ),
    ]
