# Generated by Django 4.1.7 on 2023-03-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_rename_item_category_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_picture',
            field=models.CharField(default='', max_length=100, verbose_name='Изображение категории'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='subcategory_picture',
            field=models.CharField(default='', max_length=100, verbose_name='Изображение подкатегории'),
        ),
    ]
