# Generated by Django 4.1.7 on 2023-03-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_picture',
            field=models.CharField(default='', max_length=150, verbose_name='Фото товара'),
        ),
    ]
